# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
import sys


class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")


            
        


    
        self.b_back = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_back.sizePolicy().hasHeightForWidth())
        self.b_back.setSizePolicy(sizePolicy)
        self.b_back.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        self.b_back.setObjectName("b_back")
        self.verticalLayout_2.addWidget(self.b_back)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.b_back.clicked.connect(self.go_back)  # Geri Dön butonuna tıklama işlemi bağlanıyor

        

    



       


        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_1.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_4.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_4.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_3.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_3.setObjectName("btn_page_3")
        self.verticalLayout_4.addWidget(self.btn_page_3)
        self.btn_page_4 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_4.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_4.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_4.setObjectName("btn_page_4")
        self.verticalLayout_4.addWidget(self.btn_page_4)
        self.btn_page_5 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_5.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_5.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_5.setObjectName("btn_page_5")
        self.verticalLayout_4.addWidget(self.btn_page_5)
        self.btn_page_6 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_6.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_6.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_6.setObjectName("btn_page_6")
        self.verticalLayout_4.addWidget(self.btn_page_6)
        self.btn_page_7 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_7.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_7.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_7.setObjectName("btn_page_7")
        self.verticalLayout_4.addWidget(self.btn_page_7)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")



       
        
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.grid_1 = QtWidgets.QGridLayout()
        self.grid_1.setObjectName("grid_1")
        self.label_1c = QtWidgets.QLabel(self.page_1)
        self.label_1c.setText("")
        self.label_1c.setPixmap(QtGui.QPixmap("hareketler/1d.png"))
        self.label_1c.setScaledContents(True)
        self.label_1c.setObjectName("label_1c")
        self.grid_1.addWidget(self.label_1c, 2, 1, 1, 1)
        self.label_1a = QtWidgets.QLabel(self.page_1)
        self.label_1a.setText("")
        self.label_1a.setPixmap(QtGui.QPixmap("hareketler/1a.png"))
        self.label_1a.setObjectName("label_1a")
        self.grid_1.addWidget(self.label_1a, 0, 0, 1, 1)
        self.label_1d = QtWidgets.QLabel(self.page_1)
        self.label_1d.setText("")
        self.label_1d.setPixmap(QtGui.QPixmap("hareketler/1b.png"))
        self.label_1d.setObjectName("label_1d")
        self.grid_1.addWidget(self.label_1d, 2, 0, 1, 1)
        self.label_1b = QtWidgets.QLabel(self.page_1)
        self.label_1b.setText("")
        self.label_1b.setPixmap(QtGui.QPixmap("hareketler/1c.png"))
        self.label_1b.setScaledContents(True)
        self.label_1b.setObjectName("label_1b")
        self.grid_1.addWidget(self.label_1b, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.grid_1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.grid_2 = QtWidgets.QGridLayout()
        self.grid_2.setObjectName("grid_2")
        self.label_2b = QtWidgets.QLabel(self.page_2)
        self.label_2b.setText("")
        self.label_2b.setPixmap(QtGui.QPixmap("hareketler/2a.png"))
        self.label_2b.setObjectName("label_2b")
        self.grid_2.addWidget(self.label_2b, 0, 0, 1, 1)
        self.label_2c = QtWidgets.QLabel(self.page_2)
        self.label_2c.setText("")
        self.label_2c.setPixmap(QtGui.QPixmap("hareketler/2c.png"))
        self.label_2c.setScaledContents(True)
        self.label_2c.setObjectName("label_2c")
        self.grid_2.addWidget(self.label_2c, 0, 2, 1, 1)
        self.label_2a = QtWidgets.QLabel(self.page_2)
        self.label_2a.setText("")
        self.label_2a.setPixmap(QtGui.QPixmap("hareketler/2b.png"))
        self.label_2a.setObjectName("label_2a")
        self.grid_2.addWidget(self.label_2a, 2, 0, 1, 1)
        self.label_2d = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_2d.setFont(font)
        self.label_2d.setStyleSheet("color: #FFF;")
        self.label_2d.setText("")
        self.label_2d.setPixmap(QtGui.QPixmap("hareketler/2d.png"))
        self.label_2d.setScaledContents(True)
        self.label_2d.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2d.setObjectName("label_2d")
        self.grid_2.addWidget(self.label_2d, 2, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.grid_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.grid_3 = QtWidgets.QGridLayout()
        self.grid_3.setObjectName("grid_3")
        self.label_3a = QtWidgets.QLabel(self.page_3)
        self.label_3a.setText("")
        self.label_3a.setPixmap(QtGui.QPixmap("hareketler/3b.png"))
        self.label_3a.setObjectName("label_3a")
        self.grid_3.addWidget(self.label_3a, 3, 0, 1, 1)
        self.label_3d = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_3d.setFont(font)
        self.label_3d.setStyleSheet("color: #FFF;")
        self.label_3d.setText("")
        self.label_3d.setPixmap(QtGui.QPixmap("hareketler/3a.png"))
        self.label_3d.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3d.setObjectName("label_3d")
        self.grid_3.addWidget(self.label_3d, 0, 0, 1, 1)
        self.label_3b = QtWidgets.QLabel(self.page_3)
        self.label_3b.setText("")
        self.label_3b.setPixmap(QtGui.QPixmap("hareketler/3c.png"))
        self.label_3b.setScaledContents(True)
        self.label_3b.setObjectName("label_3b")
        self.grid_3.addWidget(self.label_3b, 0, 1, 1, 1)
        self.label_3c = QtWidgets.QLabel(self.page_3)
        self.label_3c.setText("")
        self.label_3c.setPixmap(QtGui.QPixmap("hareketler/3d.png"))
        self.label_3c.setScaledContents(True)
        self.label_3c.setObjectName("label_3c")
        self.grid_3.addWidget(self.label_3c, 3, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.grid_3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.grid_4 = QtWidgets.QGridLayout()
        self.grid_4.setObjectName("grid_4")
        self.label_4d = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_4d.setFont(font)
        self.label_4d.setStyleSheet("color: #FFF;")
        self.label_4d.setText("")
        self.label_4d.setPixmap(QtGui.QPixmap("hareketler/4a.png"))
        self.label_4d.setScaledContents(True)
        self.label_4d.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4d.setObjectName("label_4d")
        self.grid_4.addWidget(self.label_4d, 0, 0, 1, 1)
        self.label_4a = QtWidgets.QLabel(self.page_4)
        self.label_4a.setText("")
        self.label_4a.setPixmap(QtGui.QPixmap("hareketler/4b.png"))
        self.label_4a.setScaledContents(True)
        self.label_4a.setObjectName("label_4a")
        self.grid_4.addWidget(self.label_4a, 1, 0, 1, 1)
        self.label_4b = QtWidgets.QLabel(self.page_4)
        self.label_4b.setText("")
        self.label_4b.setPixmap(QtGui.QPixmap("hareketler/4c.png"))
        self.label_4b.setScaledContents(True)
        self.label_4b.setObjectName("label_4b")
        self.grid_4.addWidget(self.label_4b, 0, 1, 1, 1)
        self.label_4c = QtWidgets.QLabel(self.page_4)
        self.label_4c.setText("")
        self.label_4c.setPixmap(QtGui.QPixmap("hareketler/4d.png"))
        self.label_4c.setScaledContents(True)
        self.label_4c.setObjectName("label_4c")
        self.grid_4.addWidget(self.label_4c, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.grid_4)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.grid_5 = QtWidgets.QGridLayout()
        self.grid_5.setObjectName("grid_5")
        self.label_5d = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_5d.setFont(font)
        self.label_5d.setStyleSheet("color: #FFF;")
        self.label_5d.setText("")
        self.label_5d.setPixmap(QtGui.QPixmap("hareketler/5a.png"))
        self.label_5d.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5d.setObjectName("label_5d")
        self.grid_5.addWidget(self.label_5d, 0, 0, 1, 1)
        self.label_5a = QtWidgets.QLabel(self.page_5)
        self.label_5a.setText("")
        self.label_5a.setPixmap(QtGui.QPixmap("hareketler/5c.png"))
        self.label_5a.setObjectName("label_5a")
        self.grid_5.addWidget(self.label_5a, 1, 0, 1, 1)
        self.label_5b = QtWidgets.QLabel(self.page_5)
        self.label_5b.setText("")
        self.label_5b.setPixmap(QtGui.QPixmap("hareketler/5b.png"))
        self.label_5b.setScaledContents(True)
        self.label_5b.setObjectName("label_5b")
        self.grid_5.addWidget(self.label_5b, 0, 1, 1, 1)
        self.label_5c = QtWidgets.QLabel(self.page_5)
        self.label_5c.setText("")
        self.label_5c.setPixmap(QtGui.QPixmap("hareketler/5d.png"))
        self.label_5c.setScaledContents(True)
        self.label_5c.setObjectName("label_5c")
        self.grid_5.addWidget(self.label_5c, 1, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.grid_5)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.grid_6 = QtWidgets.QGridLayout()
        self.grid_6.setObjectName("grid_6")
        self.label_6a = QtWidgets.QLabel(self.page_6)
        self.label_6a.setText("")
        self.label_6a.setPixmap(QtGui.QPixmap("hareketler/6b.png"))
        self.label_6a.setObjectName("label_6a")
        self.grid_6.addWidget(self.label_6a, 1, 0, 1, 1)
        self.label_6d = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_6d.setFont(font)
        self.label_6d.setStyleSheet("color: #FFF;")
        self.label_6d.setText("")
        self.label_6d.setPixmap(QtGui.QPixmap("hareketler/6a.png"))
        self.label_6d.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6d.setObjectName("label_6d")
        self.grid_6.addWidget(self.label_6d, 0, 0, 1, 1)
        self.label_6b = QtWidgets.QLabel(self.page_6)
        self.label_6b.setText("")
        self.label_6b.setPixmap(QtGui.QPixmap("hareketler/6c.png"))
        self.label_6b.setScaledContents(True)
        self.label_6b.setObjectName("label_6b")
        self.grid_6.addWidget(self.label_6b, 0, 1, 1, 1)
        self.label_6c = QtWidgets.QLabel(self.page_6)
        self.label_6c.setText("")
        self.label_6c.setPixmap(QtGui.QPixmap("hareketler/6d.png"))
        self.label_6c.setScaledContents(True)
        self.label_6c.setObjectName("label_6c")
        self.grid_6.addWidget(self.label_6c, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.grid_6)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.grid_7 = QtWidgets.QGridLayout()
        self.grid_7.setObjectName("grid_7")
        self.label_7a = QtWidgets.QLabel(self.page_7)
        self.label_7a.setText("")
        self.label_7a.setPixmap(QtGui.QPixmap("hareketler/7b.png"))
        self.label_7a.setObjectName("label_7a")
        self.grid_7.addWidget(self.label_7a, 1, 0, 1, 1)
        self.label_7d = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_7d.setFont(font)
        self.label_7d.setStyleSheet("color: #FFF;")
        self.label_7d.setText("")
        self.label_7d.setPixmap(QtGui.QPixmap("hareketler/7a.png"))
        self.label_7d.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7d.setObjectName("label_7d")
        self.grid_7.addWidget(self.label_7d, 0, 0, 1, 1)
        self.label_7b = QtWidgets.QLabel(self.page_7)
        self.label_7b.setText("")
        self.label_7b.setPixmap(QtGui.QPixmap("hareketler/7c.png"))
        self.label_7b.setScaledContents(True)
        self.label_7b.setObjectName("label_7b")
        self.grid_7.addWidget(self.label_7b, 0, 1, 1, 1)
        self.label_7c = QtWidgets.QLabel(self.page_7)
        self.label_7c.setText("")
        self.label_7c.setPixmap(QtGui.QPixmap("hareketler/7d.png"))
        self.label_7c.setScaledContents(True)
        self.label_7c.setObjectName("label_7c")
        self.grid_7.addWidget(self.label_7c, 1, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.grid_7)
        self.stackedWidget.addWidget(self.page_7)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_back.setText(_translate("MainWindow", "Geri Dön"))
        self.btn_page_1.setText(_translate("MainWindow", "1.egzersiz"))
        self.btn_page_2.setText(_translate("MainWindow", "2.egzersiz"))
        self.btn_page_3.setText(_translate("MainWindow", "3.egzersiz"))
        self.btn_page_4.setText(_translate("MainWindow", "4.egzersiz"))
        self.btn_page_5.setText(_translate("MainWindow", "5.egzersiz"))
        self.btn_page_6.setText(_translate("MainWindow", "6.egzersiz"))
        self.btn_page_7.setText(_translate("MainWindow", "7.egzersiz"))

        


        self.btn_page_1.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_1))
        self.btn_page_2.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_2))
        self.btn_page_3.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_3))
        self.btn_page_4.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_4))
        self.btn_page_5.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_5))
        self.btn_page_6.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_6))
        self.btn_page_7.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_7))
        
    def go_back(self): 
        
                subprocess.Popen([sys.executable, "start_menu.py"])
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
 

        
        