# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p_help.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
import sys


class Ui_Help(object):
    def setupUi(self, Help):
        Help.setObjectName("Help")
        Help.resize(1440, 900)

        self.label_photo = QtWidgets.QLabel(Help)
        self.label_photo.setGeometry(QtCore.QRect(-40, 0, 1471, 951))
        self.label_photo.setText("")
        self.label_photo.setPixmap(QtGui.QPixmap("resimler\\help.jpeg"))
        self.label_photo.setScaledContents(True)
        self.label_photo.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_photo.setObjectName("label_photo")
        self.b_1 = QtWidgets.QPushButton(Help)
        self.b_1.setGeometry(QtCore.QRect(20, 110, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.b_1.setFont(font)
        self.b_1.setStyleSheet("QPushButton {\n"
                               "    color: rgb(255, 255, 255); /* Beyaz yazı rengi */\n"
                               "    background-color: rgb(85, 170, 255); /* Hover sırasında mavi arka plan */\n"
                               "    border: 0px solid; /* Sınır yok */\n"
                               "}\n"
                               "\n"
                               "")
        self.b_1.setObjectName("b_1")
        self.label1 = QtWidgets.QLabel(Help)
        self.label1.setGeometry(QtCore.QRect(830, 60, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setStyleSheet("QLabel {\n"
                                  "    color: black; /* Siyah yazı rengi */\n"
                                  "    background-color: rgba(0, 0, 0, 0); /* Şeffaf arka plan  */\n"
                                  "}\n"
                                  "")
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(Help)
        self.label2.setGeometry(QtCore.QRect(20, 70, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setStyleSheet("QLabel {\n"
                                  "    color: black; /* Siyah yazı rengi */\n"
                                  "    background-color: rgba(0, 0, 0, 0); /* Şeffaf arka plan  */\n"
                                  "}\n"
                                  "")
        self.label2.setObjectName("label2")

        self.b_back = QtWidgets.QPushButton(Help)
        self.b_back.setGeometry(QtCore.QRect(20, 20, 100, 40))
        self.b_back.setMinimumSize(QtCore.QSize(20, 20))
        self.b_back.setSizeIncrement(QtCore.QSize(100, 40))
        self.b_back.setStyleSheet("QPushButton {\n"
                                  "    background-color: rgb(0, 0, 0); /* Siyah arka plan */\n"
                                  "    color: rgb(255, 255, 255); /* Beyaz yazı rengi */ \n"
                                  "}")
        self.b_back.setObjectName("b_back")
        self.b_back.clicked.connect(self.go_back)   # Geri Dön butonuna tıklama işlemi bağlanıyor

        self.b_3 = QtWidgets.QPushButton(Help)
        self.b_3.setGeometry(QtCore.QRect(20, 420, 331, 41))
        self.b_3.setStyleSheet("QPushButton {\n"
                               "    color: rgb(255, 255, 255); /* Beyaz yazı rengi */\n"
                               "    background-color: rgb(85, 170, 255); /* Hover sırasında mavi arka plan */\n"
                               "    border: 0px solid; /* Sınır yok */\n"
                               "}\n"
                               "\n"
                               "")
        self.b_3.setObjectName("b_3")
        self.b_6 = QtWidgets.QPushButton(Help)
        self.b_6.setGeometry(QtCore.QRect(820, 470, 421, 41))
        self.b_6.setStyleSheet("QPushButton {\n"
                               "    color: rgb(255, 255, 255); /* Beyaz yazı rengi */\n"
                               "    background-color: rgb(50, 120, 210); /* Hover sırasında mavi arka plan */\n"
                               "    border: 0px solid;\n"
                               "}\n"
                               "")
        self.b_6.setObjectName("b_6")
        self.b_7 = QtWidgets.QPushButton(Help)
        self.b_7.setGeometry(QtCore.QRect(820, 660, 421, 41))
        self.b_7.setStyleSheet("QPushButton {\n"
                               "    color: rgb(255, 255, 255); /* Beyaz yazı rengi */\n"
                               "    background-color: rgb(50, 120, 210); /* Hover sırasında mavi arka plan */\n"
                               "    border: 0px solid;\n"
                               "}\n"
                               "")
        self.b_7.setObjectName("b_7")
        self.b_5 = QtWidgets.QPushButton(Help)
        self.b_5.setGeometry(QtCore.QRect(820, 290, 421, 41))
        self.b_5.setStyleSheet("QPushButton {\n"
                               "    color: rgb(255, 255, 255); /* Beyaz yazı rengi */\n"
                               "    background-color: rgb(50, 120, 210); /* Hover sırasında mavi arka plan */\n"
                               "    border:0px solid;\n"
                               "}\n"
                               "\n"
                               "")
        self.b_5.setObjectName("b_5")
        self.b_4 = QtWidgets.QPushButton(Help)
        self.b_4.setGeometry(QtCore.QRect(820, 90, 421, 41))
        self.b_4.setStyleSheet("QPushButton {\n"
                               "    color: rgb(255, 255, 255); /* Beyaz yazı rengi */\n"
                               "    background-color: rgb(50, 120, 210); /* Hover sırasında mavi arka plan */\n"
                               "    border: 0px solid;  \n"
                               "}\n"
                               "")
        self.b_4.setAutoRepeat(False)
        self.b_4.setObjectName("b_4")
        self.b_2 = QtWidgets.QPushButton(Help)
        self.b_2.setGeometry(QtCore.QRect(20, 260, 331, 41))
        self.b_2.setStyleSheet("QPushButton {\n"
                               "    color: rgb(255, 255, 255); /* Beyaz yazı rengi */\n"
                               "    background-color: rgb(85, 170, 255); /* Hover sırasında mavi arka plan */\n"
                               "    border: 0px solid; /* Sınır yok */\n"
                               "}\n"
                               "\n"
                               "")
        self.b_2.setObjectName("b_2")
        self.label3 = QtWidgets.QLabel(Help)
        self.label3.setGeometry(QtCore.QRect(60, 750, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setStyleSheet("QLabel {\n"
                                  "    color: black; /* Siyah yazı rengi */\n"
                                  "    background-color: rgba(0, 0, 0, 0); /* Şeffaf arka plan  */\n"
                                  "}\n"
                                  "")
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(Help)
        self.label4.setGeometry(QtCore.QRect(110, 780, 321, 61))
        self.label4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label4.setStyleSheet("QLabel {\n"
                                  "    color: rgb(255, 255, 255); /* Beyaz yazı rengi */\n"
                                  "    background-color: rgb(85, 170, 255); /* Koyu gri arka plan */\n"
                                  "}\n"
                                  "")
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")

        self.l_1 = QtWidgets.QLabel(Help)
        self.l_1.setGeometry(QtCore.QRect(20, 170, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_1.setFont(font)
        self.l_1.setStyleSheet("QLabel {\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: rgba(0, 0, 0, 0); \n"
"}\n"
"")
        self.l_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_1.setWordWrap(True)
        self.l_1.setObjectName("l_1")
        self.l_2 = QtWidgets.QLabel(Help)
        self.l_2.setGeometry(QtCore.QRect(20, 320, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l_2.setFont(font)
        self.l_2.setStyleSheet("QLabel {\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: rgba(0, 0, 0, 0); \n"
"}\n"
"")
        self.l_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_2.setWordWrap(True)
        self.l_2.setObjectName("l_2")
        self.l_3 = QtWidgets.QLabel(Help)
        self.l_3.setGeometry(QtCore.QRect(20, 480, 421, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l_3.setFont(font)
        self.l_3.setStyleSheet("QLabel {\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: rgba(0, 0, 0, 0); \n"
"}\n"
"")
        self.l_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_3.setWordWrap(True)
        self.l_3.setObjectName("l_3")
        self.l_4 = QtWidgets.QLabel(Help)
        self.l_4.setGeometry(QtCore.QRect(820, 150, 421, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.l_4.setFont(font)
        self.l_4.setStyleSheet("QLabel {\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: rgba(0, 0, 0, 0); \n"
"}\n"
"")
        self.l_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_4.setWordWrap(True)
        self.l_4.setObjectName("l_4")
        self.l_5 = QtWidgets.QLabel(Help)
        self.l_5.setGeometry(QtCore.QRect(820, 350, 421, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_5.setFont(font)
        self.l_5.setStyleSheet("QLabel {\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: rgba(0, 0, 0, 0); \n"
"}\n"
"")
        self.l_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_5.setWordWrap(True)
        self.l_5.setObjectName("l_5")
        self.l_6 = QtWidgets.QLabel(Help)
        self.l_6.setGeometry(QtCore.QRect(820, 529, 421, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_6.setFont(font)
        self.l_6.setStyleSheet("QLabel {\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: rgba(0, 0, 0, 0); \n"
"}\n"
"")
        self.l_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_6.setWordWrap(True)
        self.l_6.setObjectName("l_6")
        self.l_7 = QtWidgets.QLabel(Help)
        self.l_7.setGeometry(QtCore.QRect(820, 720, 431, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_7.setFont(font)
        self.l_7.setStyleSheet("QLabel {\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: rgba(0, 0, 0, 0); \n"
"}\n"
"")
        self.l_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_7.setWordWrap(True)
        self.l_7.setObjectName("l_7")

        self.retranslateUi(Help)
        QtCore.QMetaObject.connectSlotsByName(Help)

        # Tam ekran modunu göster
        Help.show()

    def retranslateUi(self, Help):
        _translate = QtCore.QCoreApplication.translate
        Help.setWindowTitle(_translate("Help", "Help"))
        self.b_1.setText(_translate("Help", "Uygulamanın Amacı  : "))
        self.label1.setText(_translate("Help", "Sıkça Sorulan Sorular "))
        self.label2.setText(_translate("Help", "Uygulama Hakkında"))
        self.b_back.setText(_translate("Help", "Geri Dön"))
        self.b_3.setText(_translate("Help", "Nasıl kullanılır : "))
        self.b_6.setText(_translate("Help", "3. Bir egzersiz sırasında karşılaştığım sorunları nasıl çözebilirim?"))
        self.b_7.setText(_translate("Help", "4. X uygulamasını hangi cihazlarla kullanabilirim?"))
        self.b_5.setText(_translate("Help", "2. Egzersiz ilerlememi nasıl takip edebilirim?"))
        self.b_4.setText(_translate("Help", "1. Uygulama nasıl çalışır ? "))
        self.b_2.setText(_translate("Help", "Kullanıcıya Faydası : "))
        self.label3.setText(_translate("Help", "Bizimle iletişime geçin"))
        self.label4.setText(_translate("Help", "https://www.xxx.com/"))
        self.l_1.setText(_translate("Help", "X uygulaması, ortopedik, nörolojik ve travmatik rahatsızlıkları olan hastaların fiziksel rehabilitasyon sürecini desteklemek için tasarlanmış etkileşimli bir giyilebilir teknoloji ürünüdür."))
        self.l_2.setText(_translate("Help", "Bu uygulama, sakatlanma riskini azaltmaya yardımcı olur, omurga, spor yaralanmaları, denge, omuz travmaları gibi rahatsızlıklarda kişiye özel egzersiz planları ve somut veriler sunarak iyileşme sürecini hızlandırır."))
        self.l_3.setText(_translate("Help", "Uzman gözetiminde, bantlar ve sensörler vücudun ilgili bölgelerine yerleştirildikten sonra uygulama üzerinden kalibrasyon yapılır. Görsel ve işitsel biofeedback teknolojisi sayesinde kullanıcı geri bildirim alır. Ayrıca, egzersizler oyunlaştırılmış şekilde sunularak motivasyon artırılır."))
        self.l_4.setText(_translate("Help", "X uygulaması, vücuda yerleştirilen sensörler aracılığıyla fiziksel hareketlerinizi izler ve analiz eder. Bantlar ve sensörler vücudun belirli bölgelerine yerleştirildikten sonra kalibrasyon yapılır. Kalibrasyonun tamamlanmasıyla birlikte, egzersiz yaparken uygulama size görsel ve işitsel geri bildirim verir. Bu geri bildirimler sayesinde egzersizleri doğru yapmanız ve ilerlemenizi takip etmeniz sağlanır."))
        self.l_5.setText(_translate("Help", "Egzersizlerinizi tamamladıkça, uygulama her bir egzersizi otomatik olarak kaydeder ve performans verilerinizi toplar. Bu veriler, egzersiz ilerlemenizi görselleştirir ve grafikler halinde sunar. İlerleme raporlarına uygulama üzerinden istediğiniz zaman erişebilir, önceki egzersizlerle karşılaştırma yapabilirsiniz."))
        self.l_6.setText(_translate("Help", "Eğer bir egzersiz sırasında teknik bir sorun yaşarsanız ya da hareketi doğru yapmadığınızı hissederseniz, uygulama size anlık geri bildirim verecektir. Geri bildirimlere göre hareketinizi düzeltebilir veya uygulamanın yardımıyla doğru formu öğrenebilirsiniz. Eğer sorun çözülmezse, uzmanınıza danışabilir ya da uygulama içi destek hattından yardım alabilirsiniz.\n"""))
        self.l_7.setText(_translate("Help", "X uygulaması, giyilebilir sensörler ve dizüstü bilgisayar ya da tablet gibi cihazlarla uyumlu çalışır. İlgili sensörler kullanıcının vücuduna yerleştirildikten sonra, uygulama dizüstü veya tablet üzerinden kontrol edilir."))

    def go_back(self):
                subprocess.Popen([sys.executable, "start_menu.py"]) 



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Help = QtWidgets.QWidget()
    ui = Ui_Help()
    ui.setupUi(Help)
    Help.show()
    sys.exit(app.exec_())
