# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
import sys

class Ui_Profile(object):
    def setupUi(self, Profile):
        Profile.setObjectName("Profile")
        Profile.resize(1440, 900)
        Profile.setStyleSheet("Qlabel {\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.labelphoto = QtWidgets.QLabel(Profile)
        self.labelphoto.setGeometry(QtCore.QRect(-10, 0, 1471, 951))
        self.labelphoto.setText("")
        self.labelphoto.setPixmap(QtGui.QPixmap("resimler\\profile.jpeg"))
        self.labelphoto.setScaledContents(True)
        self.labelphoto.setObjectName("labelphoto")
        self.label1 = QtWidgets.QLabel(Profile)
        self.label1.setGeometry(QtCore.QRect(10, 90, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setStyleSheet("QLabel { color: rgb(85, 170, 255); /* Yazı rengi mavi / }")
        self.label1.setObjectName("label1")
        self.line1 = QtWidgets.QLineEdit(Profile)
        self.line1.setGeometry(QtCore.QRect(10, 120, 141, 31))
        self.line1.setText("")
        self.line1.setObjectName("line1")
        self.b_back = QtWidgets.QPushButton(Profile)
        self.b_back.setGeometry(QtCore.QRect(20, 20, 100, 40))
        self.b_back.setStyleSheet("QPushButton {\n"
"   color: rgb(85, 170, 255);\n"
"    border: 1px solid black; /* Koyu renkli sınır (1px kalınlıkta siyah) */\n"
"}")
        self.b_back.clicked.connect(self.go_back)  # Geri Dön butonuna tıklama işlemi bağlanıyor

        self.b_back.setObjectName("b_back")
        self.b_save = QtWidgets.QPushButton(Profile)
        self.b_save.setGeometry(QtCore.QRect(240, 660, 100, 40))
        self.b_save.setStyleSheet("QPushButton {\n"
"   color: rgb(85, 170, 255);\n"
"    border: 1px solid black; /* Koyu renkli sınır (1px kalınlıkta siyah) */\n"
"}")
        self.b_save.setObjectName("b_save")
        self.line2 = QtWidgets.QLineEdit(Profile)
        self.line2.setGeometry(QtCore.QRect(190, 120, 151, 31))
        self.line2.setText("")
        self.line2.setObjectName("line2")
        self.line3 = QtWidgets.QLineEdit(Profile)
        self.line3.setGeometry(QtCore.QRect(10, 200, 141, 31))
        self.line3.setText("")
        self.line3.setObjectName("line3")
        self.L5b1 = QtWidgets.QRadioButton(Profile)
        self.L5b1.setGeometry(QtCore.QRect(10, 280, 100, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.L5b1.setFont(font)
        self.L5b1.setStyleSheet("QRadioButton { color: rgb(85, 170, 255); /* Yazı rengi mavi / }")
        self.L5b1.setObjectName("L5b1")
        self.L5b2 = QtWidgets.QRadioButton(Profile)
        self.L5b2.setGeometry(QtCore.QRect(100, 280, 100, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.L5b2.setFont(font)
        self.L5b2.setStyleSheet("QRadioButton { color: rgb(85, 170, 255); /* Yazı rengi mavi / }")
        self.L5b2.setObjectName("L5b2")
        self.line4 = QtWidgets.QLineEdit(Profile)
        self.line4.setGeometry(QtCore.QRect(190, 200, 151, 31))
        self.line4.setText("")
        self.line4.setObjectName("line4")
        self.line6 = QtWidgets.QLineEdit(Profile)
        self.line6.setGeometry(QtCore.QRect(10, 370, 251, 31))
        self.line6.setText("")
        self.line6.setObjectName("line6")
        self.line7 = QtWidgets.QLineEdit(Profile)
        self.line7.setGeometry(QtCore.QRect(10, 460, 141, 31))
        self.line7.setText("")
        self.line7.setObjectName("line7")
        self.line8 = QtWidgets.QLineEdit(Profile)
        self.line8.setGeometry(QtCore.QRect(10, 550, 141, 31))
        self.line8.setText("")
        self.line8.setObjectName("line8")
        self.label2 = QtWidgets.QLabel(Profile)
        self.label2.setGeometry(QtCore.QRect(190, 90, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setStyleSheet("QLabel { color: rgb(85, 170, 255); /* Yazı rengi mavi / }")
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(Profile)
        self.label3.setGeometry(QtCore.QRect(10, 170, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setStyleSheet("QLabel { color: rgb(85, 170, 255); /* Yazı rengi mavi / }")
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(Profile)
        self.label4.setGeometry(QtCore.QRect(190, 170, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setStyleSheet("QLabel { color: rgb(85, 170, 255); /* Yazı rengi mavi / }")
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(Profile)
        self.label5.setGeometry(QtCore.QRect(10, 250, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setStyleSheet("QLabel { color: rgb(85, 170, 255); /* Yazı rengi mavi / }")
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(Profile)
        self.label6.setGeometry(QtCore.QRect(10, 330, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label6.setFont(font)
        self.label6.setStyleSheet("QLabel { color: rgb(85, 170, 255); /* Yazı rengi mavi / }")
        self.label6.setObjectName("label6")
        self.label7 = QtWidgets.QLabel(Profile)
        self.label7.setGeometry(QtCore.QRect(10, 430, 161, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label7.setFont(font)
        self.label7.setStyleSheet("QLabel { color: rgb(85, 170, 255); /* Yazı rengi mavi / }")
        self.label7.setObjectName("label7")
        self.label8 = QtWidgets.QLabel(Profile)
        self.label8.setGeometry(QtCore.QRect(20, 520, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label8.setFont(font)
        self.label8.setStyleSheet("QLabel { color: rgb(85, 170, 255); /* Yazı rengi mavi / }")
        self.label8.setObjectName("label8")

        self.retranslateUi(Profile)
        QtCore.QMetaObject.connectSlotsByName(Profile)

        Profile.show()

    def retranslateUi(self, Profile):
        _translate = QtCore.QCoreApplication.translate
        Profile.setWindowTitle(_translate("Profile", "Profile"))
        self.label1.setText(_translate("Profile", "Ad : "))
        self.b_back.setText(_translate("Profile", "Geri Dön"))
        self.b_save.setText(_translate("Profile", "Kaydet"))
        self.L5b1.setText(_translate("Profile", "Kadın"))
        self.L5b2.setText(_translate("Profile", "Erkek"))
        self.label2.setText(_translate("Profile", "Soyad : "))
        self.label3.setText(_translate("Profile", "T.C. "))
        self.label4.setText(_translate("Profile", "Yaş : "))
        self.label5.setText(_translate("Profile", "Cinsiyet : "))
        self.label6.setText(_translate("Profile", "Mail Adresi : "))
        self.label7.setText(_translate("Profile", "Tedaviye Başlama Tarihi: "))
        self.label8.setText(_translate("Profile", "Tedavi Bitiş Tarihi : "))

    def go_back(self):
           
        subprocess.Popen([sys.executable, "start_menu.py"]) 

        

class ProfilApp(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Profile()
        self.ui.setupUi(self)

        # "Kaydet" butonuna tıklama olayını bağla
        self.ui.b_save.clicked.connect(self.bilgileri_kaydet)

    def bilgileri_kaydet(self):
        # Kullanıcıdan bilgileri al
        ad = self.ui.line1.text()
        soyad = self.ui.line2.text()
        tc = self.ui.line3.text()
        yas = self.ui.line4.text()
        mail = self.ui.line6.text()

        # Cinsiyet bilgisi
        cinsiyet = ""
        if self.ui.L5b1.isChecked():
            cinsiyet = "Kadın"
        elif self.ui.L5b2.isChecked():
            cinsiyet = "Erkek"

        # Dosyaya kaydet
        try:
            with open("kullanici_bilgileri.txt", "a") as dosya:
                dosya.write(f"Ad: {ad}\n")
                dosya.write(f"Soyad: {soyad}\n")
                dosya.write(f"T.C.: {tc}\n")
                dosya.write(f"Yaş: {yas}\n")
                dosya.write(f"Mail: {mail}\n")
                dosya.write(f"Cinsiyet: {cinsiyet}\n")
                dosya.write("----------------------------\n")
            
            # Kaydetme başarılı olduğunda bilgi mesajı göster
            QtWidgets.QMessageBox.information(self, "Başarılı", "Bilgiler başarıyla kaydedildi!")
        except Exception as e:
            # Hata durumunda hata mesajı göster
            QtWidgets.QMessageBox.critical(self, "Hata", f"Bir hata oluştu: {str(e)}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pencere = ProfilApp()
    pencere.show()
    sys.exit(app.exec_())

